default:
  golem_name: biologicViewerSC
  golem_version: 0.0.1.0
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: Y:/working/boeings/projects/boeings/stefan.boeing/biologicShinyPlot/biologicViewerSC
